- num_prompts: 50
  prompt_length: 1000
  output_length: 150
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 50
  prompt_length: 3000
  output_length: 150
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 50
  prompt_length: 5000
  output_length: 150
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 50
  prompt_length: 8000
  output_length: 150
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 50
  prompt_length: 5000
  output_length: 1000
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 50
  prompt_length: 10000
  output_length: 500
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 50
  prompt_length: 5600
  output_length: 140
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 100
  prompt_length: 5600
  output_length: 140
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 250
  prompt_length: 5600
  output_length: 140
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 400
  prompt_length: 5600
  output_length: 140
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"

- num_prompts: 500
  prompt_length: 5600
  output_length: 140
  request_rate: "inf"
  model: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
  backend: "openai"
  base_url: "http://134.199.133.5:80"
  endpoint: "/v1/completions"


