- concurrency: 1
  num_prompts: 1
  prompt_length: 5600
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 2
  num_prompts: 1
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 4
  num_prompts: 1
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 8
  num_prompts: 1
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 16
  num_prompts: 1000
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 32
  num_prompts: 1000
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 64
  num_prompts: 1000
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 128
  num_prompts: 1000
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 256
  num_prompts: 1000
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 512
  num_prompts: 1000
  prompt_length: 200
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 1
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 2
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 4
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 8
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 16
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 32
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"


- concurrency: 64
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 128
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 256
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 512
  num_prompts: 1000
  prompt_length: 5400
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 1
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 2
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 4
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 8
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 16
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 32
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 64
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 128
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 256
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"

- concurrency: 512
  num_prompts: 1000
  prompt_length: 8000
  output_length: 140
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://129.212.188.194:8001"
  endpoint: "/v1/completions"
  