- concurrency: 1
  num_prompts: 1000
  prompt_length: 32
  output_length: 64
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://127.0.0.1:8001"
  endpoint: "/v1/completions"

- concurrency: 8
  num_prompts: 1000
  prompt_length: 32
  output_length: 64
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://127.0.0.1:8001"
  endpoint: "/v1/completions"

- concurrency: 32
  num_prompts: 1000
  prompt_length: 32
  output_length: 64
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://127.0.0.1:8001"
  endpoint: "/v1/completions"

- concurrency: 64
  num_prompts: 1000
  prompt_length: 32
  output_length: 64
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://127.0.0.1:8001"
  endpoint: "/v1/completions"


- concurrency: 128
  num_prompts: 1000
  prompt_length: 32
  output_length: 64
  request_rate: "inf"
  model: "deepseek-ai/DeepSeek-V3-0324"
  backend: "openai"
  base_url: "http://127.0.0.1:8001"
  endpoint: "/v1/completions"
