apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server
  template:
    metadata:
      labels:
        app: vllm-server
    spec:
      hostIPC: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: amd.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: vllm-container
        image: rocm/vllm:rocm6.4.1_vllm_0.10.0_20250812
        ports:
        - containerPort: 8000
        command: ["bash"]
        args:
        - "-c"
        - "cd / && vllm serve deepseek-ai/DeepSeek-V3-0324 --tensor-parallel-size 8 --block-size 1 --enable-prefix-caching --enable-prompt-tokens-details"
        env:
        - name: HF_HOME
          value: "/data"
        - name: VLLM_ROCM_USE_AITER_RMSNORM
          value: "0"
        - name: VLLM_USE_V1
          value: "1"
        - name: VLLM_ROCM_USE_AITER
          value: "1"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret-new
              key: token
        - name: GPU_ARCHS
          value: "native"
        resources:
          limits:
            amd.com/gpu: 8
        volumeMounts:
        - name: data
          mountPath: /data
        - name: shm
          mountPath: /dev/shm
        - name: dev-kfd
          mountPath: /dev/kfd
        - name: dev-dri
          mountPath: /dev/dri
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          seccompProfile:
            type: Unconfined
      securityContext:
        supplementalGroups:
        - 44  # video group GID
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 60
      volumes:
      - name: data
        emptyDir: {}
      - name: shm
        emptyDir:
          medium: Memory
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
      - name: dev-dri
        hostPath:
          path: /dev/dri