
apiVersion: v1
kind: Service
metadata:
  name: vllm-external
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "vllm-server"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
spec:
  type: LoadBalancer
  selector:
    app: vllm-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
